# Generated by Django 4.2.10 on 2024-03-03 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="profile_picture",),
    ]
